#!/usr/bin/env bash

# file: script_test_oedo_3
# author: JBC @ NORTHWESTERN UNIVERSITY, (jibril.coulibaly@gmail.com)
# Script calling LAMMPS to perform oedometric tests simulations
#
# Copyright (C) 2023 Mechanics and Energy Laboratory, Northwestern University
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# This script is not standalone. It must be used in conjunction with the master
# script that defines all the variables used herein, and executes this script
# through the command `source`
#
# The scripts are written in bash. This is out of generality to be able to
# perform the simulations both in Windows platforms that have consoles that
# can run bash, and on GNU/Linux platform or WSL where bash is default/native
#
# - TODO:
# - 
#
# =========================================================================== #
#

$lmp_run \
-in in.MAIN_test_oedo_3 \
-var path_out "'$path_out'" \
-var fname_suffix "'$fname_suffix'" \
-var file_restart "'$file_restart'" \
-var var_param_oedo_3 ${var_param_oedo_3[*]} \
-var var_init_material_3 ${var_init_material_3[*]} \
-var var_init_boundary_3 ${var_init_boundary_3[*]} -var file_wall "'$file_wall'" \
-var var_param_simulation_3 ${var_param_simulation_3[*]} \
-var var_param_BC_control_3 ${var_param_BC_control_3[*]} \
-var var_param_equilibrium_3 ${var_param_equilibrium_3[*]} \
-log "${path_out}/log.test_oedo_3${fname_suffix}.lammps" \
-echo $echo_option \
$screen_option
